### ISSUE TITLE
Question: Best way to make a complete Backup/Migrate to new drive?

### ISSUE THREAD

**Issue by ChojinDSL** [gamer-os/gamer-os#101]
Hi, is there a recommended way to make a backup if you want to migrate the gameros install to a new drive or new system?

I figure a simple rsync might not work because during installation Drive and Partition UUIDs are used. Would it suffice to simply backup everything in the /home/gamer directory, install from scratch on a new system, then copy everything back to /home/gamer?

Would that also restore any roms and flatpaks added via steam buddy?

**Comment by alkazar** [comment]
You would just need to copy /home/gamer unless you made some kind of customizations.
