### ISSUE TITLE
WOL support

### ISSUE THREAD

**Issue by DaedalusHyperboreus** [gamer-os/gamer-os#102]
I've enabled WOL support for my network card by installing ethtool and adding the following lines from the Archlinux Wiki:
```
/etc/udev/rules.d/81-wol.rules
ACTION=="add", SUBSYSTEM=="net", NAME=="enp*", RUN+="/usr/bin/ethtool -s $name wol g"
```

It would be nice if this could be added to the standard build.

**Comment by alkazar** [comment]
That would be interesting.

I had a look through the Arch wiki page, but there is something basic I don't understand. What is the purpose of the udev rule? Wake on LAN only comes into play when the computer is off, udev along with everything else is not running at that point. I would have thought this was an option that needs to enabled in the computer bios and that is it.

**Comment by DaedalusHyperboreus** [comment]
Without the rule, the network device is created with deactivated WOL ("Wake-on: d").
With the rule the WOL flag is set upon creation of the network device. So when the system is shutdown the network card listens for the magic packet (as long as the system is not cut from power so the flag is reset, I guess).

**Comment by alkazar** [comment]
@DaedalusHyperboreus Wake on Linux support is included in the latest release in the testing repo. It would be great if you could test it out before I push it to the stable repo.

You can switch to the testing repo using the instructions here: https://github.com/gamer-os/gamer-os/wiki/FAQ#how-can-i-help-test-gameros

**Comment by DaedalusHyperboreus** [comment]
I've switched to gameros-18_dd74953 and can confirm that WOL is working on my machine.

**Comment by alkazar** [comment]
Great! Thank you for testing!

**Comment by DaedalusHyperboreus** [comment]
After the release of GamerOS 18 I should be able to seamlessly switch back to the stable repo, right?

**Comment by alkazar** [comment]
@DaedalusHyperboreus No, it will stay on the testing repo. You can switch back to stable, but the way you do that will change with the new update. I will update the instructions once the release is out.

If you switch back now, you will get downgraded to GamerOS 17.
