### ISSUE TITLE
Got GamerOS running in VMware Fusion 11.5

### ISSUE THREAD

**Issue by sucram65** [gamer-os/gamer-os#103]
I had put this aside for a few weeks after successfully installing but having no video output. What I did on a 2019 MacBook Pro 16 inch was two things. First I went to energy saver and disabled "Automatic Graphics Switching" so that the AMD GPU is always active while on AC power. Next, I shut down the vm and opened it's settings to enable "Accelerate 3D Graphics." I also changed the "Shared Graphics Memory" setting the the recommended 768MB. When I started the vm again the window manager started successfully and I could see the Steam UI come up and launch big picture. I thought there was going to be a lot more to getting this running but it turned out to be fairly simple. This should work in Workstation as well.

**Comment by alkazar** [comment]
Closing since no action required.
