### ISSUE TITLE
Laggy UI

### ISSUE THREAD

**Issue by r-giskard-reventlov** [gamer-os/gamer-os#105]
I've just installed gamer-os but I'm having issues with the BPM lag. For a few seconds at a time the interface is responsive on the keyboard however most of the time there is a lag of about 5 seconds between pressing a key and the UI responding.
Ive noticed that this only occurs once I log in, i.e. I can browse the options presented at the login screen with no issues.
My machine is this: https://support.hp.com/hk-en/document/c04017240 (quad core version). I've run SteamOS on the perfectly, I just wanted to upgrade for newer drivers.
I'm afraid I have no way of posting logs as the UI doesn't allow me to exit to the desktop even though I can see the menu option from BPM.

**Comment by alkazar** [comment]
Do you have the machine connected to a 4k display?

**Comment by r-giskard-reventlov** [comment]
no, it was a 1080p tv

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by alkazar** [comment]
@r-giskard-reventlov Is this still a problem?
