### ISSUE TITLE
The internet is wrong

### ISSUE THREAD

**Issue by xer0-1ne** [gamer-os/gamer-os#108]
Four of the best Linux gaming OSes?!?  He clearly overlooked one....... This should have been on the top of the list.  Arch Linux, Steam integration, ROM support, easy controller mapping.... 

https://opensource.com/article/20/5/linux-gaming#comment-203071

**Comment by alkazar** [comment]
Uhh... not sure what you want me to do about this, lol.

**Comment by alkazar** [comment]
Thanks for the support!
