### ISSUE TITLE
Nintendo Switch Pro Controller keeps disconnecting

### ISSUE THREAD

**Issue by zefrieira** [gamer-os/gamer-os#111]
Hi @alkazar! I've just installed GamerOS and my experience has been great. Thank you for your work!

I'm having, however, a problem with the bluetooth connection of my Nintendo Switch Pro Controller. It keeps disconnecting out of nowhere and I couldn't identify what is triggering this. I'm using a USB bluetooth dongle.

**Comment by alkazar** [comment]
Could it be related to #71 ?

Are you able to try the work around noted there?

**Comment by zefrieira** [comment]
I did try it, but the controller keeps disconnecting. Later today I'll try to test another controller with the 8bitdo adapter (I've never tried it in Linux, so I'll also test it on a Ubuntu installation).

**Comment by alkazar** [comment]
The only other thing I can think of is that there is just a poor connection to the dongle. Is the dongle plugged into the back of your system? If so, consider plugging it in somewhere there is a direct line of sight from the controller to the dongle.

I have also seen my fair share of poor quality dongles.

**Comment by zefrieira** [comment]
The 8bitdo adapter worked fine, the problem was indeed the dongle. Thank you!
