### ISSUE TITLE
Steam overlay and popup notifications are white 

### ISSUE THREAD

**Issue by alkazar** [gamer-os/gamer-os#112]
When you bring up the Steam overlay, the screen is completely white. You are still able to select options (I can hear sound) but can't see anything.

Similarly, in-game Steam popup notifications are completely white.

This started happening with the June 1 Steam update.
It only seems to affect Nvidia. My computer with an AMD GPU continues to show the overlay and notifications correctly.

Upstream bug report:
https://github.com/ValveSoftware/steam-for-linux/issues/7169

**Comment by arendjr** [comment]
I can confirm the same thing happens on SteamOS (also on Nvidia).

**Comment by TheExplodingPixel** [comment]
Can confirm, with a GTX1060, same issue.

**Comment by daddeltrotter** [comment]
Same here with GTX950 using gamer-os

Not happening with my old laptop NVIDIA GT218M [NVS 3100M] running Steam Client on Kubuntu, hence I assume it's a driver issue.

**Comment by alkazar** [comment]
I have confirmed the issue also happens using the original, unmodified steamos compositor.

**Comment by xer0-1ne** [comment]
Same issue.  As of today.  Nvidia GTX 1050Ti.

White screen for overlay and white boxes for popups.  I can navigate the menu and hear the sounds.

**Comment by andreashuetter** [comment]
I am having the same issue. Is there any solution or workaround yet?

**Comment by deathxxx123** [comment]
With a GTX1060, same issue.
With Ubuntu, no problem.

**Comment by andy3471** [comment]
Same issue on a fresh install with a GTX 980.

**Comment by dragonfly-lover** [comment]
The same happens to me. I have Ubuntu 18.04 + steamos compositor.

**Comment by alkazar** [comment]
This has now been fixed in the latest Steam client beta.

**Comment by alkazar** [comment]
Looks like the fix was pushed to all Steam clients now.
