### ISSUE TITLE
Need Help Downloading

### ISSUE THREAD

**Issue by Onemadlink** [gamer-os/gamer-os#113]
This is so far the best OS I've seen for controllers. I'm trying to download files off of the internet using this though for gaming. I tried using the steam web browser but that didn't do too well for downloading. Any help would be more than appreciated!

**Comment by alkazar** [comment]
You have a few options:
 - install Firefox from Flathub and use that
 - use the `curl` command from the command-line
 - download the files on another computer and transfer to your GamerOS machine with ssh or ftp

What kind of files are you downloading? And what do you intend to do with those files?

**Comment by Onemadlink** [comment]
Well idk if it's against the rules for me to say here, but oh yeah man, they're roms lol. I am big time into retro gaming. I for some reason can't get the ftp transfer setup in steam buddy. Firefox also for some reason won't let me download, and I can't get the drop down box on its own internal settings.

**Comment by alkazar** [comment]
Application menus do not work with the compositor turned on. You can toggle it off through Steam Buddy (it is an option under the cog menu).

Why not download game content on another device and upload it via Steam Buddy? It is a lot easier to manage and add games to Steam through Steam Buddy.
