### ISSUE TITLE
Keyboard layout

### ISSUE THREAD

**Issue by daddeltrotter** [gamer-os/gamer-os#114]
After installation of gamer-os, language is set to German but still the keyboard layout is English.
I still use a keyboard for gaming, entering login data etc. so using the keyboard is sometimes in a blind way.

I can't remember that I could enter a locale during set-up and as I have already downloaded several games, I'm hesitating to redo installation.

Did I miss something during installation? Then I will do reinstall of course.
If not, can I change the keyboard layout in gamer-os?

**Comment by alkazar** [comment]
Hi, sorry about that, but we don't provide a way to set the keyboard layout easily. You will need to set things up on the command line.

Please take a look at the instructions here:
https://wiki.archlinux.org/index.php/Linux_console/Keyboard_configuration

**Comment by daddeltrotter** [comment]
Hi. Thanks a lot for the quick reply and the link.
I fixed it manually with the following steps:
- press `ctrl-alt-f3` to open a tty
- login with username `gamer` and password `gamer`
- run `sudo frzr-unlock` to change the system to read-write mode
- run `sudo localectl set-x11-keymap de pc105 deadgraveacute` to change the X11 keymap
- reboot

So for me the keyboard is working fine.
What remains potentially open is the locale:
The system locale is set currently to `en_US.UTF-8`. I did not change it because there are no other locale definitions available in `/etc/locale.gen`. Maybe by intention? 
It looks like they come with glibc. I'm not at all knowledgeable on linux distribution creation, so I stopped at this point :).
My initial problem is solved and up to now, I don't see issues with this locale.

**Comment by alkazar** [comment]
I don't think you need to run `frzr-unlock`.

Regarding locale, I think you can set your language in Steam and that will change the language in games as well or there is also a separate language option for each game. There are actually some Linux games that break if you change the locale.
