### ISSUE TITLE
SSH access

### ISSUE THREAD

**Issue by gamersalpha** [gamer-os/gamer-os#116]
Hello i m just installed steamOs on my old laptop, how to connect SSH to adding some roms for emulation gaming please ?

**Comment by alkazar** [comment]
If you connect to the Steam Buddy web UI and click on the cog icon in the top right and select "Settings" you can set up SSH or FTP access there.

**Comment by alkazar** [comment]
I wouldn't recommend adding games through SSH though, it is much easier to use the web interface. You can still add games manually by creating shortcut files. See instructions here: https://github.com/gamer-os/steam-tweaks#steam-shortcuts-steam-shortcuts

**Comment by gamersalpha** [comment]
COol works, i got faileds update i dont know how many time, but looks works
