### ISSUE TITLE
EXT GDC compatible - On pc portable with gemeros

### ISSUE THREAD

**Issue by gamersalpha** [gamer-os/gamer-os#117]
Hello there i got an old pc portable, i bought a extgdc system to some new card graphics on the laptop
but how install driver on my gameros ?

thanks all

**Comment by alkazar** [comment]
Sorry, I don't know what you mean. What is "EXT GDC"?
You can't really install additional drivers on GamerOS.

**Comment by gamersalpha** [comment]
look this : https://www.youtube.com/watch?v=Vitm76idHBU

for now not working on my laptop :/

**Comment by alkazar** [comment]
Oh, an external GPU. The first thing to figure out is if it works on Linux in general and what it requires to set it up if anything.

If it is supposed to work out of the box, then the issue is probably because GamerOS doesn't support hybrid graphics setups. This is covered in #97
