### ISSUE TITLE
Dreamcast - Ho wto Change settings ?

### ISSUE THREAD

**Issue by gamersalpha** [gamer-os/gamer-os#119]
Hello there, when i lunch dreamcast game i got a little windows to play ?

how to change resolution please : 

Shenmu : 
![image](https://user-images.githubusercontent.com/32466950/84573447-bf0e9d00-ada0-11ea-975b-5cedcacf1d77.png)

Sonic 2 
![image](https://user-images.githubusercontent.com/32466950/84573470-e9f8f100-ada0-11ea-9d75-55953eb1051f.png)

tha'ts works, 
but how to chang in fulls screen

thanks

**Comment by alkazar** [comment]
You can copy `/usr/share/steam-buddy/config/retroarch-common.cfg` to `~/.config/steam-buddy/retroarch-common.cfg` and change `video_scale_integer = "true"` to `video_scale_integer = "false"`

**Comment by gamersalpha** [comment]
sorry VIM i can't , please how install nano ?

**Comment by alkazar** [comment]
You can temporarily install nano with the following series of commands:
`sudo frzr-unlock`
`sudo pacman -Sy`
`sudo pacman -S nano`

All changes will be reverted after the system is updated though.

**Comment by alkazar** [comment]
I'll include nano in the next update.
