### ISSUE TITLE
I have to use the keyboard to update the system manually

### ISSUE THREAD

**Issue by alkazar** [gamer-os/gamer-os#12]
Updating the system is awkward and requires dropping to a terminal and use of a keyboard.

Updates should happen automatically, be safe, and never require any user intervention.

**Comment by alkazar** [comment]
Updating the system is awkward and requires dropping to a terminal and use of a keyboard.

Updates should happen automatically, be safe, and never require any user intervention.

**Comment by alwayslivid** [comment]
Cron jobs could do the trick here.

**Comment by alkazar** [comment]
@alwayslivid no, that is not enough. The upgrade process may need user intervention, or it could break. This happens occasionally with Arch. Even if we based this on Ubuntu or another, more stable system, things can go wrong. Especially during upgrades between releases, like Ubuntu 16.04 -> Ubuntu 18.04, not to mention it takes hours to upgrade.

I want to investigate atomic updates using ostree, similar to Fedora Silverblue.

**Comment by alkazar** [comment]
implemented using https://github.com/gamer-os/frzr
