### ISSUE TITLE
Troubleshoot?

### ISSUE THREAD

**Issue by Wazz4657** [gamer-os/gamer-os#120]
Reformatted my SteamOS box and am now trying GamerOS due to drivers. A lot of things aren't working, didn't want to open an issue for each. Wondering how to troubleshoot non-launching games? For instance:

Darkest Dungeon - crashes after Intro.
Every Arcade ROM I've tried - hangs on "Loading Machine 45%"
GalCiv 3 - Crashes after start screen

Obviously this wouldn't work in gamerOS, however in SteamOS in these cases I would drop to the desktop and try to run from the command line, can usually see what the problem is. DD especially I'm sure is something simple.

Or is the solution actually to just submit these findings to GitHub for someone else to look at?

**Comment by alkazar** [comment]
Darkest Dungeon: Looking at the protondb page it looks like the native Linux version of this game crashes on many different distros. People are running it with proton instead.

Arcade ROMs: Many MAME Roms depend on other ROMs. I encountered this myself. Unfortunately, the emulator software doesn't report what files are missing.

Galactic Civilization III: Looking at the protondb page, it seems this game requires the use of proton 3.16

In general, if you want to debug you could do one of two things:
 - look at the log files in ~/.local/share/Steam/logs
 - add the included terminal program as a shortcut through the Steam UI and launch the terminal to run commands through the command line
