### ISSUE TITLE
[ SOLVED ]Failed TO START INITIALIZE PACMAN KEYRING

### ISSUE THREAD

**Issue by Aspylum** [gamer-os/gamer-os#122]
EDIT: IT TURNED OUT TO BE THE MOTHERBOARD, IDK IF IT JUST WASNT COMPATIBLE, BUT IT WOULD LOAD UP WINDOWS. BUT I SWAPPED THEM OUT AND IT WORKS NOW.                                                    I get to the INSTALL GamerOS screen I hit enter, It goes through the steps... Everything has a green [ok] behind everything except one..its " Failed to start initialize pacman keyring"
then after a few seconds, it cuts to a black screen with a blinking cursor on the top left. I've tried everything in the bios. Can someone please help!!! BTW the blinking cursor is infinite it doesn't do anything else. I also have a wired internet connection.

**Comment by alkazar** [comment]
@Aspylum How did you solve this problem?

**Comment by dahlellama** [comment]
I am having the same issue. I have tried using both legacy and UEFI boot methods. I have reset my motherboard bios and swapped to different hard drives.
System:
Dell T3600
8 core Xeon E5 - 2665
32GB RAM 
AMD RX580
