### ISSUE TITLE
Wake On USB support

### ISSUE THREAD

**Issue by ENKI101** [gamer-os/gamer-os#123]
Standby + Wake On USB support possible?
Best regards

**Comment by sharkwouter** [comment]
Steam does not actually allow you to put the machine in standby, so this would be very hard to implement.

**Comment by alkazar** [comment]
If your bios supports it, I believe you can setup "wake on usb" even from a completely off state.
As sharkwouter mentioned, Steam and GamerOS do not support sleep or standby mode.
