### ISSUE TITLE
Change primary Monitor

### ISSUE THREAD

**Issue by metageetaku** [gamer-os/gamer-os#127]
I'd like to play on my TV, but gamerOS only use my old laptop monitor.

How can i change VGA to be the primary monitor?

Thanks in advance.

**Comment by alkazar** [comment]
Sorry, it is not really possible at this time.

**Comment by metageetaku** [comment]
Thank you for your response.

Sorry if my question is dumb, but since it is linux based, why X is not included? I tried Xrandr before asking here, but the answer is always "can't open display".

**Comment by alkazar** [comment]
X is definitely included. You need to specify the display since you are on the command line.

So something like:
`DISPLAY=:0 xrandr`

**Comment by arthurlutz** [comment]
Is there a workaround for this using the SSH connection ? Could https://github.com/ChimeraOS/chimera/issues/28 with https://github.com/ChimeraOS/steamos-compositor-plus#configuration be a work around ?
