### ISSUE TITLE
GloriousEggroll

### ISSUE THREAD

**Issue by xpdos** [gamer-os/gamer-os#128]
Is there a way to load custom proton versions? I added the file via ftp and added it to the steam/root dir in a folder named compatibilitytools.d but does not appear in the dropdown. not really a issue, more of a question but did not see any answers to this in the forums.

**Comment by alkazar** [comment]
It should pick it up. Perhaps you need to restart?
Did you extract the compressed file first?

**Comment by xpdos** [comment]
Yeah, I am a idiot I extracted it the first time but forgot to extract the tar file. Worked flawlessly after I did it the correct way. Thanks for the helpful quick response, Loving the project it has brought new life back to my alpha.
