### ISSUE TITLE
Can't open Steam overlay on emulated on Flatpak and emulators

### ISSUE THREAD

**Issue by smumu** [gamer-os/gamer-os#129]
Using a Steam Controller, it's difficult, sometimes impossible, to open the Steam Overlay.

On emulators, the only way I found is tu shutdown my Steam Controller and restart it, so Steam opens it overlay when the controller connects. Tested on Gamecube, PS2, Game Boy Color, Game Boy Advance and Atari 2600, all have the problem.

On Flatpak games, it is possible to open it by spamming the Steam button on the controller (seems random). Tested on StepMania, Minetest, Veloren and SuperTuxKart.

This makes exiting the game and managing controller mapping really difficult.
A possible fix to exit the game is to connect to Steam Buddy but when an emulator or a Flatpak app is launch, the password doesn't show on TV (compositor problem?) so you have to disable security or remember to login on Steam Buddy before launching the game.

**Comment by CullenJWebb** [comment]
I'm having a similar issue, the overlay does not open at all while using a Xbox One controller via USB or the Xbox One wireless adapter.

**Comment by alkazar** [comment]
Does everyone affected by this have an AMD GPU?
Strangely, with an Nvidia GPU, I am able to open the overlay (albeit it is white due to another bug), but on an AMD GPU I am not able to open it in steam shortcuts.

**Comment by CullenJWebb** [comment]
I'm running integrated Intel graphics. 

I tried button mashing the guide button like what was mentioned earlier and I did eventually get the overlay to appear, but only once.

**Comment by smumu** [comment]
I use an AMD GPU, not integrated (Radeon VII) with an AMD CPU (Ryzen 7 3800X) if it can help.

**Comment by alkazar** [comment]
@smumu Does this still happen? It seems to have gotten fixed by Valve for all my systems now.

**Comment by smumu** [comment]
@alkazar Is it a simple Steam update? 
I'm not at home so I'll give it a try in one or two weeks.

**Comment by CullenJWebb** [comment]
@alkazar I'm able to test this today. I'll let you know how it goes.

**Comment by smumu** [comment]
@alkazar sorry for the delay, I could try today. It works fine now.
Tested on 2 flatpak applications, 1 gamecube game and 1 PS1 game.
