### ISSUE TITLE
Cannot log in with long pass with special symbols

### ISSUE THREAD

**Issue by deathxxx123** [gamer-os/gamer-os#130]
I just need to reset my pass to simpler one, then I succeed to log in steam.

**Comment by alkazar** [comment]
How are you logging in, with a keyboard? Could it be the keyboard layout?

**Comment by deathxxx123** [comment]
Yes, with KB with US layout.
Maybe because pass was 32 words and digits long. Or maybe, because it has special symbols in it. But in normal steam client in ubuntu i can log in with long pass.
Now is like 10 symbols and can log in with no problem.

**Comment by alkazar** [comment]
In any case, it sounds like this is not something we can do anything about. You can try filing a bug here: https://github.com/ValveSoftware/steam-for-linux/issues
