### ISSUE TITLE
How to unmute, muted middle speakers with 5.1 config?

### ISSUE THREAD

**Issue by deathxxx123** [gamer-os/gamer-os#131]
My sound card have alwayis muted middle sound with any distro by default. So I need unmute in alsamixer, but in this OS, does not have alsamixer. How to do that?

**Comment by deathxxx123** [comment]
Don't have amixer too.
Only have pulsemixer, but this program do not have ability to mute/unmute only Center speaker. Only can do that on all speakers, but that will not unmute the Center speaker.
Only Alsamixer and Amixer can do this.
Sound Card: Auzentech Prelude 7.1 (with Creative X-Fi [20K1] chipset)

**Comment by deathxxx123** [comment]
I search for some help in the web and find something that can help:
[(https://bugs.launchpad.net/ubuntu/+source/pulseaudio/+bug/677067/comments/4 )]
But i do not see the:
/src/modules/alsa/mixer/paths/analog-output.conf

**Comment by deathxxx123** [comment]
I found how to clear this bug(to install alsamixer):
`sudo pacman -S alsa-utils`
Then i can open alsamixer in terminal and unmute my center speaker!
Also i found the `analog-output.conf`
in
`/frzr_root/deployments/gameros-18_a89413e/usr/share/pulseaudio/alsa-mixer/paths`
and add the
```
[Element Center/LFE]
switch = mute
volume = merge
override-map.1 = center,lfe
```
as root, save and exit. (because for my card, center channel is not only `Center` or `LFE` like other cards, but it's `Center/LFE` instead. So, because that is missing in `analog-output.conf` , the center sound are always muted after clean install.

**Now i have center sound in 5.1 sound configuration!**

**Comment by deathxxx123** [comment]
I guess, you can include this, by default:
```
[Element Center/LFE]
switch = mute
volume = merge
override-map.1 = center,lfe
```
in `analog-output.conf` by default, to fix muted center speaker for others who have Creative X-FI cards.

**Comment by alkazar** [comment]
I will include `alsa-utils` in the next release, but I am not sure how the proposed configuration will impact other users.

**Comment by deathxxx123** [comment]
> I will include `alsa-utils` in the next release, but I am not sure how the proposed configuration will impact other users.

I think that will not harm anyone. If you edit the `analog-output.conf` to fix X-Fi cards Center, to get sound with 2.1, 4.1, 5.1, 7.1 and any configuration that uses Center/Subwoofer.
That is just miss mapping Center speaker for X-fi cards. Maybe the devs can finally add this in `analog-output.conf` by default, like other cards.

**Comment by deathxxx123** [comment]
Great news. Looks like they will merge this change to pulseaudio or whatever.. So this cards will finally have a better support!
https://gitlab.freedesktop.org/tanuk/pulseaudio/-/commit/8e04a72f06365c7bd442508d8c5b3fc12bb13f00

**Comment by alkazar** [comment]
Closing since there is no further action to take. Thanks!
