### ISSUE TITLE
PowerA Xbone controllers not recognized

### ISSUE THREAD

**Issue by Wazz4657** [gamer-os/gamer-os#132]
Hi,

I've got 2 of these, they stopped working after I switched from SteamOS. I'm having the exact same behavior mentioned here:

https://github.com/paroj/xpad/issues/48

No input from the controller. The machine does recognize it, but it seems like it keeps initializing over and over again.
 
I believe there was a patch to xpad that fixes it: 

https://github.com/cgutman/xpad/tree/powera

Thanks!

**Comment by alkazar** [comment]
Is this controller wired or wireless?

**Comment by Wazz4657** [comment]
Both are wired. I can send the dmesg output, if that helps.

**Comment by alkazar** [comment]
This will have to be fixed in the kernel. Does this still happen in GamerOS 19?

**Comment by Wazz4657** [comment]
It does not, actually. Everything is working perfectly now. Thanks!
