### ISSUE TITLE
Can't boot after install

### ISSUE THREAD

**Issue by conscript93** [gamer-os/gamer-os#134]
Tried to install gamer-os on my AMD APU build, and it fails to initialize after install. It fails to start LightDM and stops the boot sequence. Checking the systemctl status for lightdm.service, it reports "Start request repeated too quickly."
The computer has a first gen triple-core AMD A6 3500 with Radeon HD 6530D graphics processor, on an AsRock A55M-HVS motherboard. 
I'm not really experienced in Arch, but if any logs or files are needed, I can provide them.
Thanks!

**Comment by sharkwouter** [comment]
Unfortunately, this GPU is not supported by GamerOS. There might be a fix for it, but I'm not sure about how that would work.

**Comment by conscript93** [comment]
Thanks for the reply! This GPU is supported by the opensource radeon driver on the Debian derivatives I tried. Is it possible to install this driver on GamerOS? I don't understand much of Arch, and pacman does not seem to work because of frzr. Is there a workaround?
Thanks!

**Comment by sharkwouter** [comment]
You could use ``sudo frzr-unlock`` and try to install/activate it somehow, but if there is an update your changes will be undone.

**Comment by alkazar** [comment]
You should be able to enable it by removing the `blacklist radeon` line in the file `/etc/modprobe.d/system-tweaks.conf`. No need for `sudo frzr-unlock`.

However, the GPU is old and does not support Vulkan.
