### ISSUE TITLE
How to install Proton-GE to GamerOS? To what directory?

### ISSUE THREAD

**Issue by deathxxx123** [gamer-os/gamer-os#135]
I need to install custom Proton to play Borderlands 3, but i dont know where should place the files...
Directory in steam are different for this OS.

**Comment by alkazar** [comment]
There is nothing special about GamerOS and the Steam directories. It is the same as any other distro.
These instructions should work: https://github.com/GloriousEggroll/proton-ge-custom#native

**Comment by deathxxx123** [comment]
Yes i fugured it out after some research.
In Ubuntu patch are:
`$HOME/.steam/root/compatibilitytools.d/`
In GamerOS path are:
`$HOME/.local/share/Steam/compatibilitytools.d/`
