### ISSUE TITLE
Sign Out Of Chat

### ISSUE THREAD

**Issue by Kung-Foo-Kamel** [gamer-os/gamer-os#136]
Hi, 

On the desktop interface of Steam we can sign out of chat permanently, but in BPM there is no option that I can find to do this, I don't want to use the feature and I normally have it signed out on Windows installs, is there anyway to do this in Gamer-OS?

**Comment by alkazar** [comment]
Sorry, I can't make any changes to the Steam client, you would have to file a bug with them. Try here: https://github.com/ValveSoftware/steam-for-linux/issues
