### ISSUE TITLE
Black screen on Intel iGPU on Pentium G3258

### ISSUE THREAD

**Issue by mangomctango** [gamer-os/gamer-os#137]
Hi fellas,

_Summary: Failed to start Steam Patch Service for gamer & Failed to start Light Display Manager._

I've installed GamerOS quite a few times on an Intel G3258 system (no dGPU), and the installation goes well with one thing that popped up about binding HDMI driver (something to that extent).

Anyway, the main issue is that once it reboots, I get a black screen. SOMETIMES I get a mouse cursor or a flashing Steam logo screen.

ALT+F1 = Flashing cursor in the top left.
ALT+F2-F6 = TTY
ALT+F7 = Black screen

- I've accessed TTY and checked to see that LightDM is Active. `systemctl status lightdm.service`
- `frzr-unlock` removes point below
     - Pacman won't work until I `mkdir /var/lib/pacman`
     - Pacman won't work without `--overwrite '*'`. It throws a exists in system.
- Installed  `xf86-video-intel `and uninstalled and reinstalled, etc.
- Removed and reinstalled LightDM.
- `Included uxa in /etc/X11/xorg.conf.d/20-intel.conf`
- Uninstalled and reinstall steam-tweaks.
- `systemctl status steam-patch.service` shows unit not found.

Confused.😕

**Comment by rshamsnejad** [comment]
> the installation goes well with one thing that popped up about binding HDMI driver (something to that extent).

What do you mean by that ? Do you have a screenshot or photo of that message ?

>       * Pacman won't work until I `mkdir /var/lib/pacman`
>       * Pacman won't work without `--overwrite '*'`. It throws a exists in system.

That's expected, as Pacman is not supposed to be used in GamerOS. Although it is based on Arch packages, it does not use the package manager in the end-user image.

>     * `systemctl status steam-patch.service` shows unit not found.

I believe the correct unit name is `steam-patch@gamer.service`, but I may be wrong as I can't test right now.

**Comment by mangomctango** [comment]
I reinstalled with an old Nvidia card and the error did not appear. but the error was very similar to this one. Might be exact.
>` snd_hda_intel 0000:00:03: HSW/BDW HD-audio HDMI/DP requires binding with gfx driver` [Source](https://bbs.archlinux.org/viewtopic.php?id=232461)

However, the main issues are still there. Failed to start steam patch and lightdm.

I haven't tried to reinstall or update yet. I will once I get home this afternoon.

**Comment by alkazar** [comment]
Is this still an issue?

**Comment by mangomctango** [comment]
I installed an nvidia gpu and the problem went away. I'm certain it's an arch and intel driver issue. I've had similar issues with Manjaro on a Surface L3 with an i7.

**Comment by kendalnix** [comment]
Hi.

I think I have the same problem.

After install GamerOS (gameros-2020.10.02-x86_64.iso) all I get is a black screen with two errors:
```
[FAILED] Failed to start Light Display Manager
[FAILED] Failed to start Steam Patch Service for gamer

```
According to `inxi` my GPU is:

`Advanced Micro Devices [AMD/ATI] Cedar [Radeon HD 5000/6000/7350/8350 Series]`

while my CPU is:

`Topology: Dual Core model: Intel Core2 6420 bits: 64 type: MCP L2 cache: 4096 KiB 
           Speed: 2128 MHz min/max: N/A Core speeds (MHz): 1: 2128 2: 2129 `

Is there any way to fix the problem?

Thanks in advance

**Comment by alkazar** [comment]
It doesn't look like your GPU is supported. You could try the following:
1. start your GamerOS box with a keyboard attached
2. after the error appears, press `ctrl-alt-f3` on the keyboard
3. open `/etc/modprobe.d/system-tweaks.conf` with nano or vim
4. edit the file by removing the line `blacklist radeon` and save the file
5. run `reboot` to restart the system

**Comment by kendalnix** [comment]
> It doesn't look like your GPU is supported. You could try the following:
> 
>     1. start your GamerOS box with a keyboard attached
> 
>     2. after the error appears, press `ctrl-alt-f3` on the keyboard
> 
>     3. open `/etc/modprobe.d/system-tweaks.conf` with nano or vim
> 
>     4. edit the file by removing the line `blacklist radeon` and save the file
> 
>     5. run `reboot` to restart the system

Hi.

Thanks for you quick reply.

After remove the `blacklist radeon` line, I finally got GamerOs working.

Thank you so much.

**Comment by alkazar** [comment]
No problem. Just know that your GPU does not support Vulkan. You may not have the best experience.

**Comment by rshamsnejad** [comment]
Indeed, a lot of games won't work without Vulkan. Some Proton games can be made to work by adding `PROTON_USE_WINED3D=1` to the launch options though.

**Comment by kendalnix** [comment]
Thanks for the help and tips. 
One last question, maybe a bit offtopic. In case I get a GPU with Vulkan support, which one would be ideal? If not a specific model, which chipset/series? 
Thanks in advance.

**Comment by mangomctango** [comment]
Is this your CPU? If so, it's from 2007. So any modern GPU will be badly bottlenecked. Afaik Radeon HD 7000 & Nvidia Kepler are the oldest GPUs that support Vulkan. 

- https://ark.intel.com/content/www/us/en/ark/products/29755/intel-core-2-duo-processor-e6420-4m-cache-2-13-ghz-1066-mhz-fsb.html

- https://www.youtube.com/watch?v=L5rRewNmhXY

You can check if a GPU has Vulkan support on TPU.
 - https://www.techpowerup.com/gpu-specs/radeon-hd-7850.c1055

**Comment by kendalnix** [comment]
Yes, that's my CPU. I had Steam installed in that PC running Linux for a while, just for playing some basic arcade games, nothing serious. 

I like the idea of GamerOS of having a gaming system with Steam and emulators integrated, all with a controller compatible interface. But again, it's just for playing some basic, undemanding games. 

Thanks. 

PS: far away from the US, but thanks for the tip.
