### ISSUE TITLE
Ethernet card not supported

### ISSUE THREAD

**Issue by moonwolf-github** [gamer-os/gamer-os#139]
ETH interface on MSI MPG Z490 mainboard is not supported (it doesn't even appear in system).

`lspci` shows it as `Realtek RTL8125 2.5GbE (rev 04)`

**Comment by moonwolf-github** [comment]
Forgot to add - it's in installer.

**Comment by moonwolf-github** [comment]
After installation it still doesn't work.

**Comment by alkazar** [comment]
The best I would be able to do is create new installer images based on latest Arch.

Could you check if you can get a network connection on the latest Arch Linux install media, that is what the GamerOS install media is based on.

**Comment by moonwolf-github** [comment]
According to https://askubuntu.com/questions/1259947/cant-get-rtl8125b-working-on-20-04 driver sould land in kernel 5.9. So i guess we'll have to wait.

**Comment by moonwolf-github** [comment]
Sorry to spam comments but i see mainline kernel i arch repos so i'll give it a try (after crash course in Arch administration).

**Comment by moonwolf-github** [comment]
OK, i can confirm that with kernel 5.9 interface is recognized and works OK. I guess i'll close this issue as it has nothing to do with GamerOS.
