### ISSUE TITLE
Adding non-steam games to Steam library

### ISSUE THREAD

**Issue by ENKI101** [gamer-os/gamer-os#140]
Is that possible via CLI or BPM?
Or do I have to use desktop mode?

**Comment by alkazar** [comment]
It depends what kind of games you want to add.

Using Steam Buddy you can add ROMs for various pre-installed and pre-configured emulators, or install a selection of Flathub apps.

If you want to install additional non-Steam games, take a look here:
https://github.com/gamer-os/steam-tweaks#steam-shortcuts-steam-shortcuts

It may be easiest to add some games via Steam Buddy (using some dummy data) then use the resulting shortcut yaml files as a reference when creating your own.

The shortcuts do not yet support specifying a proton version or configuration, but this feature has been implemented for the upcoming release.

**Comment by ENKI101** [comment]
Thank you! Solved my problem.
Just created the yaml files in steam-shortcuts folder as described in the link above.
