### ISSUE TITLE
No apps in flathub/new

### ISSUE THREAD

**Issue by Altokos** [gamer-os/gamer-os#142]
Hello there,

First for all, thank you for youre job, it's very great. So I'm here because I have an issue with Steam Buddy and GamerOS, the flathub/new tab in steam buddy is completely blank.

Any idea on how I can solve this ?

**Comment by alkazar** [comment]
Sorry, this issue is fixed in an upcoming version.

This seems to happen when Steam Buddy starts and cannot obtain an internet connection.
You can try "Restart Steam" from Steam Buddy, which might fix it.

**Comment by horriblejohnny** [comment]
having the same issue. loving GamerOS by the way

**Comment by bboyles303** [comment]
Also having this problem. Any idea when a fix is coming? Or is there a way to force an update?

**Comment by horriblejohnny** [comment]
GamerOS 20 is out. Steam Buddy works now. Just update your system.

**Comment by Altokos** [comment]
It's working great with the new release.
