### ISSUE TITLE
Keyboard in qwerty

### ISSUE THREAD

**Issue by Altokos** [gamer-os/gamer-os#143]
Hello again,

I'm french and in France most of people uses azerty keyboards instead of qwerty.

When I installed GamerOs I choses the french language but the keyboard is set in qwerty layout.

So I edited _/etc/vconsole.conf_ with _KEYMAP=fr_ but after few reboots the keyboard is in qwerty again.

Could you help me with that ?

**Comment by rshamsnejad** [comment]
Hi ! I'm French and I have the same problem. I already reported it, but @alkazar argued that a keyboard is not supposed to be necessary in GamerOS, so this setting wasn't introduced in the install process.

**Comment by Altokos** [comment]
But I have to solve other problems like the bluetooth connectivity which does not work, it requires that I have the right layout for my keyboard for more "productivity"

**Comment by rshamsnejad** [comment]
You can still SSH into your GamerOS system as a workaround. You can set it up through Steam Buddy.

**Comment by Altokos** [comment]
Sure it's a good idea
