### ISSUE TITLE
Proton-GE won't run games

### ISSUE THREAD

**Issue by Altokos** [gamer-os/gamer-os#146]
Hi,

I've downloaded Proton-GE 5.9 and 5.11 and the games won't launch in steam.

I've read somewhere that is an issue with Arch and Proton-GE is it right ?

Do you know how I can solve it ?

Thanks.

**Comment by Altokos** [comment]
I solved this issue by extracting the files on the GamerOS PC. Before that I was uploading to it with the ftp the extracted files.

**Comment by sharkwouter** [comment]
Oh, that makes sense. Ftp does not preserve permissions.
