### ISSUE TITLE
Steam Controller not working

### ISSUE THREAD

**Issue by maweki** [gamer-os/gamer-os#152]
I tried to use my steam Controller with GamerOS and it doesn't work. Neither through USB cable (which works on my Fedora box) nor connection through the dongle. Other controllers on the same (powered) hub work fine. Steam asked me to power the controller though, which makes me think the dongle was discovered (haven't checked with `lsusb` yet).

I think under Fedora I needed to install the kernel-extras package, but I am not sure.

**Comment by alkazar** [comment]
That is strange. My Steam controller works out of the box and I know it works for others too.

What exactly happens when you turn the controller on? Does the Steam logo turn on fully or is it flashing?

**Comment by maweki** [comment]
> What exactly happens when you turn the controller on? Does the Steam logo turn on fully or is it flashing?

Steam asks me to power the controller while pressing X. When I do this, the Steam logo on the Controller flashes for just a millisecond.

**Comment by alkazar** [comment]
That sounds like the batteries are dead. Are you sure you are using good
batteries?

**Comment by maweki** [comment]
Okay, so the batteries I thought were rechargeable weren't, and they were indeed dead. And the cable which I thought worked, didn't.

Replaced both. Both wired and wireless work fine now.
