### ISSUE TITLE
New arch version

### ISSUE THREAD

**Issue by moonwolf-github** [gamer-os/gamer-os#155]
Tehere is new arch version available with kernel 5.9.2 which should resolve issues with some network cards (#139). Do you plan to build new GamerOS based on this new veriosn?

**Comment by moonwolf-github** [comment]
Hmm... Looks like despite annoucement on steam there's no new release available.

**Comment by alkazar** [comment]
The install media is independent from the system releases. The install media just downloads the latest available release and installs it.

I will be doing an install media refresh in the next few weeks.

**Comment by moonwolf-github** [comment]
Ah. OK, sorry for the fuss.
