### ISSUE TITLE
Feature: Enable Lutris-Support?

### ISSUE THREAD

**Issue by stevleibelt** [gamer-os/gamer-os#160]
Hey,

via watching the Arch Conf 2020 Videos, I found your great project.
Since I am mostly buying and using gog.com, I am using lutris as general game launcher. I have totally no clue if this feature request is ever possible. But right after reading your project, I thought "if this would be in, I would be in" :-).

**Comment by alkazar** [comment]
Lutris is not possible to support, but GOG support is currently being added to Steam Buddy. See https://github.com/gamer-os/steam-buddy/issues/39
