### ISSUE TITLE
Can you run a plex server in the background?

### ISSUE THREAD

**Issue by doggonator** [gamer-os/gamer-os#162]
I'd imagine this is the wrong place to ask this, but if it can do it, that'd be perfect.

I'd also like to run a tmux session that I manually start through SSH, is this possible?

Again really sorry for the dumb question.

**Comment by alkazar** [comment]
GamerOS has a read-only root file system. As such you cannot install additional software except by installing it to your home directory, for example through Flatpak or AppImage.

GamerOS does not include plex nor tmux currently and I am not sure it would make sense to given the intended use case.

What you could do is fork this repo, modify the `manifest` file to add in the additional packages you want and build your own custom OS images.

**Comment by doggonator** [comment]
That's fair enough, my use case is defintely an odd one and I agree it wouldn't make much sense for the purposes of the OS. Thank you for taking the time to reply, I really appreciate it.

I'll close the issue.

**Comment by Tau5** [comment]
I am also interested in running a media server in the background on GamerOS, although in my case I wanted to use Jellyfin for the server, which is an open-source alternative to Plex
