### ISSUE TITLE
Wrong time

### ISSUE THREAD

**Issue by mwprado** [gamer-os/gamer-os#164]
I live in Brazil, my fuse is UTC -3 and GamerOS point to UTC -8 (Vancouver) and can't fix time of my computer in steam big picture.

**Comment by alkazar** [comment]
Unfortunately, Steam doesn't reflect the change immediately. Set the time to your preferred timezone and then restart your computer to apply the change. Opening the timezone settings again will reset to the default setting of UTC -8 Seattle i.e. Valve's HQ timezone.
