### ISSUE TITLE
[Request] Add rsync util to the base installation of GamerOS.

### ISSUE THREAD

**Issue by qchto** [gamer-os/gamer-os#166]
Hey there,

I'm the maintainainer of [a "simple" script on GitLab](https://gitlab.com/qchto/steam-disk-lib-utils) that's focused in allowing among other things, assisted downloads of compatibility tools for Steam Linux (ie. Proton-GE), hotswapping of steam libraries from other devices (including external drives) and (more important for the case) **backup and restore of steam games from preset libraries**.

Given that all these features are possible in GamerOS. I'm currently testing them with great results so far, including the addition of local libraries and download of some compatibility layers-, but had to make use of "frzr-unlock" to install rsync in order to get the backup/restore functionality. So, I'd like to **request the base installation to provide rsync utility preloaded**, as this script is intended to be used **out-of-the-box** by as many linux gaming enthusiasts as possible under most distros (which I'm sure overlaps with your work).

PS: I'm relatively new at this so sorry if there's other way to make these request directly.

**Comment by alkazar** [comment]
Thanks for the suggestion, done!
