### ISSUE TITLE
Broadcom Wifi Adapter BCM43xx BCM4360 how to get it to work?

### ISSUE THREAD

**Issue by pareis** [gamer-os/gamer-os#171]
I'm trying to connect to Wifi using my BCM4360 adapter, normally this would require some manual installation steps, like listed here: https://wiki.archlinux.org/index.php/Broadcom_wireless

How would I achieve this in GamerOS, given that rootfs is read-only?

**Comment by alkazar** [comment]
What are the actual steps you would need to do?
/etc is actually read-write, but not sure that helps.
Do you need the firmware packages?

**Comment by pareis** [comment]
I need to install either https://archlinux.org/packages/?name=broadcom-wl or https://archlinux.org/packages/?name=broadcom-wl-dkms - I'm not sure which one exactly now but I know I had one of them working in the Ubuntu or Fedora flavours of my Linux installs.

I could be on a wired connection during install so that wouldn't be the issue but for regular use I'd need to be on Wifi (due to lack of ethernet connectivity at the place of gaming).

**Comment by alkazar** [comment]
I will include `broadcom-wl` in the next build. Not sure when that will be though as there are currently some unrelated issues. I'll ping this issue when it is ready for testing. Thank you for reporting.

**Comment by alkazar** [comment]
@pareis the new testing build includes the broadcom drivers. Are you able to test?
Instructions for switching to the `testing` channel can be found here:
https://github.com/gamer-os/gamer-os/wiki/FAQ#how-can-i-help-test-gameros
