### ISSUE TITLE
Thermals and Undervolt

### ISSUE THREAD

**Issue by Minnietheandroid** [gamer-os/gamer-os#173]
Hi. I'm wondering if it is possible to run intel-undervolt on gamer-OS?
The system installs and runs very well on a 2019 HP-Omen laptop, but I couldn't find a way to adjust for thermals.
On both Linux and Windows I've gotten around it running hot by undervolting the cpu and limiting the clock speed.

**Comment by TheCraiggers** [comment]
Can you adjust the values as needed in the BIOS?

**Comment by Minnietheandroid** [comment]
Thanks for the reply.
Sadly no. HP Omen gaming laptops a have locked down bios.
Instead they use a software based undervolt in their 'Omen Command Center' for 2019/2020 models.

I've been using intel-undervolt from the repo in Manjaro, (does the same thing as throttlestop/XTU.) 
But I can't see any way to install it on gamer-OS.
Shame. it runs incredibly well otherwise, so I thought I'd ask.

**Comment by alkazar** [comment]
I am including the `intel-undervolt` package in the next build since it is so tiny.

**Comment by Minnietheandroid** [comment]
This is great news! Made my day. Thanks so much for your help :)
