### ISSUE TITLE
cannot connect to wifi networks

### ISSUE THREAD

**Issue by alkazar** [gamer-os/gamer-os#18]

**Comment by sharkwouter** [comment]
This seemed like a polkit issue, but I've tried a couple of configuration and they don't seem to solve the issue. I made sure the polkit service is running. I tried the following configuration files:


```
polkit.addRule(function(action, subject) {
  if (action.id.indexOf("org.freedesktop.NetworkManager.") == 0 && subject.isInGroup("wheel")) {
    return polkit.Result.YES;
  }
});
```

```
polkit.addRule(function(action, subject) {
  if (action.id == "org.freedesktop.NetworkManager.settings.modify.system" &&
	subject.local && subject.active && 
	subject.isInGroup ("wheel") ) {
    return polkit.Result.YES;
  }
});

```

This first of these was found on the [Arch wiki](https://wiki.archlinux.org/index.php/NetworkManager#Set_up_PolicyKit_permissions). The last one if the configuration as found in SteamOS.

I also tried installing network-manager-applet, but that didn't change the behaviour either.

**Comment by alkazar** [comment]
I took a crack at this issue.

I first tried to make this work on my standard Arch install. I was actually able to successfully connect to a wifi network using the SteamOS interface by installing `lib32-libnm`.

On gamerOS, I tried installing `lib32-libnm` and also adjusting the polkit settings as @sharkwouter did above, but I could not connect. I tried on 2 different computers to rule out some hardware/driver issues.

The error I could see in `journalctl` was `802-11-wireless.mac-address: connection does not match device`. Googling that error led nowhere.

At least we know it is possible to get this to work.

**Comment by alkazar** [comment]
I tried comparing the list of network related packages installed on my Arch install where wifi works vs gamerOS. I tried installing the following packages on gamerOS:
 - `network-manager-applet`
 - `net-snmp`
 - `nm-connection-editor`
 - `libnma`

Still can't connect to wifi in gamerOS.

**Comment by sharkwouter** [comment]
I found that Steam uses the libnm-glib library. This library is no longer supported by the NetworkManager maintainers. In the changelog for NetworkManager I found the following statement:
```
The libnm-glib library, deprecated in favor of libnm since NetworkManager 1.0,  and disabled by default since NetworkManager 1.12, has now been removed.
```
Source: https://github.com/NetworkManager/NetworkManager/blob/05175562f504491fc4a7d7f6811481b1fcb3a63f/NEWS

It is possible to install this library, since it is still in the Arch repo, but it doesn't seem to fix the problem. The package offers version 4.9.0, while SteamOS uses 4.8.0. I wasn't able to load the SteamOS version on Arch. I was hoping installing this library would fix the issue, since the error mentioned in this issue is one of the errors I'm seeing: https://github.com/ValveSoftware/steam-for-linux/issues/4968

**Comment by sharkwouter** [comment]
SteamOS ships NetworkManager version 0.9.10.0. The easiest way to fix the issue might just be to adapt the PKGBUILD used by Arch to install a similar version.

I found the release tag for version 0.9.10.2 in the Github repo of NetworkManager: https://github.com/NetworkManager/NetworkManager/releases/tag/0.9.10.2

**Comment by sharkwouter** [comment]
I found out that it is possible to get old PKGBUILD files from the official Arch repo. You can get all the source files for the packages in the Arch repo with ``git clone https://git.archlinux.org/svntogit/packages.git``.

**Comment by alkazar** [comment]
I was curious to see if this has been resolved, so I tested GamerOS 10.

I was successfully able to detect and connect to wifi networks. There must have been a Steam client update at some point that addressed this issue.

The problems with detecting password protected networks is also completely fixed.

**Comment by coolguy-terabit** [comment]
when i first installed today the networks wont show up ad i cant use ethernet
