### ISSUE TITLE
Firefox DRM content

### ISSUE THREAD

**Issue by wallzero** [gamer-os/gamer-os#182]
Firefox seems to have trouble installing the DRM files in order to play DRM content such as Netflix. I am not sure if this is caused by the read only nature of the system directories or if a dialogue confirmation isn't being rendered correctly (issue related to #181).

**Comment by alkazar** [comment]
This is Firefox installed through Flathub? Is this an issue specific to GamerOS or specific to the flatpak version of Firefox?

**Comment by wallzero** [comment]
Sorry after switching the compositor and further testing this turned out to be a DNS issue on my end.
