### ISSUE TITLE
Add fsync support

### ISSUE THREAD

**Issue by Samsagax** [gamer-os/gamer-os#184]
As [stated in the Arch Wiki](https://wiki.archlinux.org/index.php/Steam#Fsync_patch) the current default kernel `linux` does not have the Fsync patch that could improve performance in many games. The Arch repositories have a community package for the zen kernel `linux-zen` that is up to date and has the patch and menu other improvements for schedulers and governors. That of course will need the `-dkms` versions of kernel modules outside the tree (like the `nvidia` package that has official `nvidia-dkms` support).

Personally I use it exclusively on my setup without issues and even ditched the vanilla kernel package.

**Comment by Klairm** [comment]
Fsync support could cause issues, there are some games that doesn't work with fsync for example Yakuza 0 won't allow to save if fsync is enabled, and  editing the launch options for disable fsync isn't a couch experiencie imo

**Comment by alkazar** [comment]
Let's be patient, new fsync patches are being worked on and upstreamed.
