### ISSUE TITLE
downloading GamerOS via BusyBox

### ISSUE THREAD

**Issue by JohnnyDilinjer** [gamer-os/gamer-os#186]
Hi. I have a question:
I have installed GamerOS on external HDD. I have my kernel and initramfs. Can I load my BusyBox (kernel + initramfs) and mount sda2 (GamerOS (root)) and then use switch_root?

**Comment by alkazar** [comment]
Sorry, I don't understand what you are trying to accomplish, but please use the kernel and initramfs included with GamerOS.
