### ISSUE TITLE
Unable To Login Into Steam Account Using VirtualBox

### ISSUE THREAD

**Issue by intelligentgaming** [gamer-os/gamer-os#188]
Hi everyone, I know that GamerOS states that virtual machines are not supported but for the purpose of producing a review of this distribution I wanted to trial it first in VirtualBox before installing it on actual hardware.

But I'm stuck at the login screen for Steam, as I cannot type in my user name or password, I can click on the fields but typing using a keyboard does not register. 

Is there an option to bring up an on screen keyboard or am I stuck?

**Comment by alkazar** [comment]
Sorry to hear that. That is quite strange.

One thing with VMs is sometimes the mouse and keyboard focus can switch between the host and guest, most likely this is not the issue but something to double check.

Another option might be to connect to the VM with Steam Buddy, click on the cog icon and select "Virtual Keyboard".
You can connect to Steam Buddy by opening a browser and typing in the IP address of the GamerOS VM.

Good luck!

**Comment by intelligentgaming** [comment]
OK, just to rule out VirtualBox, I installed GamerOS using KVM, and the same issue occurs. 

Strangely, I can install everything but as soon as it comes to signing in, my keyboard does not work. 

I tried the Steam Buddy but even the Virtual Keyboard does not send to the VM.

Really puzzled?

**Comment by alkazar** [comment]
I had a VM I was using for some backend testing and fired up the UI. I can confirm this happens, but no idea why.
Sorry, but I don't think I will be putting any effort towards fixing this.

**Comment by intelligentgaming** [comment]
Fair enough, I'll have to find another method of testing it.
