### ISSUE TITLE
Protontricks How to?

### ISSUE THREAD

**Issue by Mohandevir** [gamer-os/gamer-os#195]
Hi!

Is there an "How To" to install/use Protontricks on GamerOS?

Long story short, my kids would like to run Lego: Lord of the Rings but it requires the following tweak:
protontricks 214510 d3dx9_41

I tried different things, but since GamerOS is not a full fledged Arch and considering It's the only Arch based distro I use, I'm a litlle at a loss.

Is there anything I can do about it?

**Comment by sharkwouter** [comment]
You could technically use the AUR package. You would need to run ``sudo frzr-unlock`` on the terminal or on ssh and the changes you make will be lost if there is an update, though. I don't really have a good answer for this.

Could you explain how Protontricks is used? Is it controller friendly? It might be worth adding to GamerOS, but it depends on how usable it is in our use-case.

**Comment by Mohandevir** [comment]
I would have a hard time explaining how it works in detail, but long story short, It's Proton's Winetrick. Once installed you can issue commands like the one I supplied to add tweaks to the game's Proton prefix.

This is what I use to install it on my Pop_OS! install:
https://github.com/Matoking/protontricks

**Comment by alkazar** [comment]
This can now be done using protonfixes which is built into Proton GE. LEGO Lord of the Rings specifically had a fix merged into the latest Proton GE.
