### ISSUE TITLE
Feature Request : Add pacman compatibility

### ISSUE THREAD

**Issue by Xenoxis** [gamer-os/gamer-os#197]
Currently, pacman doesn't work :
`> pacman
error : failed to initialize alpm library
(could not find or read directory: /var/lib/pacman/)` 

and we can't install package from Archlinux repository. Installing package is, in the current state, a pain. It will be great to add this compatibility.

**Comment by sharkwouter** [comment]
You can use pacman, but you'll need to run ``sudo frzr-unlock`` first to make the root partition no longer read only. Then if there is an update, any changes to the system which were made using pacman will be removed from the system. It's not great, but it does work.

**Comment by Xenoxis** [comment]
Ok, thanks for the answer, it worked !
