### ISSUE TITLE
no uefi support

### ISSUE THREAD

**Issue by alkazar** [gamer-os/gamer-os#20]

**Comment by wb7odyfred** [comment]
https://www.plop.at/en/bootmanagers.html. Look at his new bootmanager.   I also like supergrub2 UEFI boot file that you copy to the ESP EFI partition.


Copy file to the EFI fat32 boot partition among the other UEFI boot files.  Use this supergrub2_x86-64.EFI boot file to help select / manage which partition you wish to boot when grub is borked.  Supergrub2 will search and display all the bootable partition/files and give you the choice to select which one to boot.
https://sourceforge.net/projects/supergrub2/files/2.02s10/super_grub2_disk_2.02s10/super_grub2_disk_standalone_x86_64_efi_2.02s10.EFI/download


Have you looked at ConvergenceOS bash shell script for turning a Debian 9.6-9 , Ubuntu 18.03, Linux Mint 19.1 into a game controller based big picture STEAM game play from the couch.

 https://github.com/wb7odyfred/ConvergenceOS
What I forked from  John Bitzen
https://github.com/jonbitzen/ConvergenceOS/issues/1
Best Wishes, Fred
You project was mentioned on Linux for everyone Telegram group channel.
https://github.com/gamer-os/gamer-os
Anybody know anything about this distro or tried it?

**Comment by wb7odyfred** [comment]
https://t.me/linux4everyone/5118

**Comment by alkazar** [comment]
implemented in gamerOS 5
