### ISSUE TITLE
Cannot write to /etc/modprobe.d/system-tweaks.conf

### ISSUE THREAD

**Issue by tylerhein** [gamer-os/gamer-os#203]
Logging in as gamer/gamer, I can not edit /etc/modprobe.d/system-tweaks.conf using nano.

nano states, File '/etc/modprobe.d/system-tweaks.conf' is unwritable.

**Comment by tylerhein** [comment]
Tried vim.
when saving with the :w command, I receive E505: "/etc/modprobe.d/system-tweaks.conf" is read only.
Tried :w! command, E212: can't open file for writing.

**Comment by sharkwouter** [comment]
Try using sudo

**Comment by tylerhein** [comment]
Yup. Fixed it.
