### ISSUE TITLE
Mangohud.conf where is it?

### ISSUE THREAD

**Issue by hawari21** [gamer-os/gamer-os#206]
Hello moderator,

So today i was installed gamer os which is pretty awsome, and i did some test of my games with mangohud which is you need to press F3 to toggle it. However, i noticed that there is only few basic info, such as fps, cpu usage and gpu usage. So i want to adding more option like ram usage, ect but i cant find it anywhere. I've use another distro to access frfrz_root partition and search for mangohud.conf but i cant find it.

Could you tell me where is locate?

**Comment by alkazar** [comment]
There is no mangohud configuration file included by default.

The mangohud documentation says that the config file should be here:
$HOME/.config/MangoHud/MangoHud.conf

**Comment by BrunoHernandez** [comment]
I wonder if anyone has managed to modify the default configuration yet?
I created the following file [f] (/home/gamer/.config/MangoHud/MangoHud.conf) based on [reference](https://raw.githubusercontent.com/flightlessmango/MangoHud/master/bin/MangoHud.conf):
I also tried forcing environment variable for path at startup (before calling steamcompmgr):
`export MANGOHUD_CONFIGFILE=/home/gamer/.config/MangoHud/MangoHud.conf
`

[f]
```
### Display the current CPU information
cpu_stats
cpu_temp
cpu_power

### Display the current GPU information
gpu_stats
gpu_temp
gpu_power

fps
frametime

frame_timing
#histogram

font_size=24
position=top-left
### Hud transparency / alpha
background_alpha=0.4
# alpha=

```

**Comment by Samsagax** [comment]
I found that [this line](https://github.com/gamer-os/steamos-compositor-plus/blob/8a9d9eeb37b660a52af818bfe9d8bae5dfc9d319/usr/bin/steamos-session#L10) prevents the use of any config file unless that variable is override.

@alkazar maybe you should add a default config file in the home directory by copying the one provided by MangoHud, or no file at all but delete that variable so a config file could be used. Maybe integrating a configuration companion in steam-buddy?

**Comment by alkazar** [comment]
Oh, I see. One work around might be to add `export MANGOHUD_CONFIG=` to `~/.config/steamos-compositor-plus`, or specify the configuration you want there.

**Comment by Samsagax** [comment]
I think the best way is to leave it alone. I mean delete that line, don´t set any configuration in the compositor and leave the default. Like this example from the MangoHud Readme:
![](https://github.com/flightlessmango/MangoHud/blob/master/assets/overlay_example.gif)

Then optionally the user (or an app made for that ;) like steam-buddy) could write a file `.config/MangoHud/MangoHud.conf` to configure it to his/her liking.

Even the line above (the one that says `export MANGO_HUD=1`) could be deleted from there and instruct the user (or again, steam-buddy) to put that variable inside `~/.config/environment.d/MangoHud.conf` file as stated in [the ArchWiki](https://wiki.archlinux.org/index.php/Environment_variables#Per_user) so systemd will set them.
