### ISSUE TITLE
Feature request: add file editing tools

### ISSUE THREAD

**Issue by GrinningDantist** [gamer-os/gamer-os#207]
One of the things I like about PC gaming is modding support. But it's impossible without a proper file manager and a notepad. Can you add something like Nautilus and Geany?

**Comment by alkazar** [comment]
GamerOS is meant to be controlled by a gamepad so it doesn't really make sense to include this by default.
If you want to do file manipulation, your options are:
- use a tty
- use ftp
- use ssh
- install the Dolphin file manager from Flathub

**Comment by GrinningDantist** [comment]
Fair enough.
