### ISSUE TITLE
GamerOS desktop mode?

### ISSUE THREAD

**Issue by massatt212** [gamer-os/gamer-os#211]
I cant find Desktop Mode, i want to add Proton Ge 6.4

**Comment by alkazar** [comment]
There is no desktop mode.

Your options are:
1. use  ssh/command line to install proton ge (https://github.com/gamer-os/gamer-os/wiki/GamerOS-Troubleshooting#gameros-system-maintenance)
2. wait for the next release of GamerOS which will include Proton GE 6.4
