### ISSUE TITLE
Feature request: Audio control

### ISSUE THREAD

**Issue by Mohandevir** [gamer-os/gamer-os#217]
Hi!
I would like to know if there could be a way to add an optionnal audio volume control to GamerOS (Steam buddy maybe?). I've been able to make it work with xbindkeys and it allowed me to use the Steam controller (Steam button + Stick up & down) to adjust the volume while playing.

Just pasting here the solution I used and another user (Joe136), with better knowledge than I do, did something cleaner. He even found a way to modify SteamOS' default volume level (it's all in the last 3 comments):

https://github.com/ValveSoftware/SteamOS/issues/146

Thanks anyway; I really appreciate your work.

**Comment by alkazar** [comment]
There are already is volume control in Steam Buddy.

**Comment by Mohandevir** [comment]
Oups! Sorry then... Missed it.

Happy to learn about it.

Thanks!
