### ISSUE TITLE
[request] Lutris install scripts

### ISSUE THREAD

**Issue by zany130** [gamer-os/gamer-os#225]
I know lutris would not be practical to support, but what about somehow making lutris install scripts work? Some games need a lot of proton tweaks to run for example legend of heroes is one game. This is the main deternet for me using gameros

**Comment by alkazar** [comment]
I don't think it is practical to use Lutris install scripts. Many of the scripts require GUI steps or keyboard/mouse interaction which would not work on a gamepad controlled system or be a sub-optimal experience.

GamerOS has steam-tweaks which can work in the background for a better experience.
