### ISSUE TITLE
create a logo and website

### ISSUE THREAD

**Issue by alkazar** [gamer-os/gamer-os#24]
Create a simple static site hosted on github.

**Comment by ohnozen** [comment]
I could potentially help with this. I've attached some logo ideas I've been playing with. These are definitely first draft logos, but I'd be more than happy to explore these further or going in a different direction if you have something else in mind.

![gamer-os_logos](https://user-images.githubusercontent.com/14218478/64662996-edc1a680-d40f-11e9-8724-d8b96ff288b7.png)

**Comment by alkazar** [comment]
Wow, those are very creative logos, thanks for your effort! But I feel like they are very difficult to read. I think something a bit simpler might be better.

**Comment by ohnozen** [comment]
Something more like a wordmark? I'll work out some simple type and icon solutions.

**Comment by alkazar** [comment]
@Sandaidev I appreciate the effort but we cannot use the Steam logo to represent gamerOS.

**Comment by ohnozen** [comment]
I've simplified the designs a bit, and focused more on type in one version. I still wanted to explore the D-Pad looking designed, so I focused more on the Steam Controller look.

The buttons are currently Game Boy colored, but I've built them to work in monochrome or any other color style.

![gamer-os_logo_u1](https://user-images.githubusercontent.com/14218478/64859098-f1f7ea80-d5ee-11e9-8e7d-180479e65d5c.png)

**Comment by sharkwouter** [comment]
Wow, those are amazing

**Comment by alkazar** [comment]
Wow, I really like the dpad G design. So much I think we should rename from
"gamerOS" to "GamerOS". It is simple, clever, and creative. Nice job!

Could you try some alternatives where the dpad is a bit shorter/less
pronounced? I am wondering how that would look.

**Comment by ohnozen** [comment]
Thanks for the kind words! I always enjoy projects like these.

Here are some with shorter D-Pad stems (and one with thinner stems) and with a disconnected pad.

Original alone to the left. I personally like the top two alternates, but I'd be happy with any of these.

Let me know if you'd like more alternate versions.
![gamer-os_logo_alt](https://user-images.githubusercontent.com/14218478/64861227-0b039a00-d5f5-11e9-8880-ce39b475ebc1.png)

**Comment by alkazar** [comment]
I agree, I like the top two. I like the look of the top left one best, but it is less readable as a "G".

Perhaps try extending the notch just a little bit, or make the gap a tiny bit smaller?

I am also curious what it might look like if the dpad was smaller, say, 3/4 or even half the size, but still centered. You would also probably have to make the stroke width of the whole thing thinner though.

**Comment by ohnozen** [comment]
Sure thing. I've extended the notch and reduced the D-Pad stems to 3/4 size. Also trying weight variations.
![gamer-os_logo_alt_u1](https://user-images.githubusercontent.com/14218478/64866814-b0d1fb80-d62b-11e9-849e-68fe5f15d066.png)

**Comment by alkazar** [comment]
I like the two on the right. Thanks for doing up all these versions! I have a bunch more ideas I would love to see, but feel free to ignore if it is getting to be too much:

1. dpad weight that is in between the right two above
2. play with the gap between the dpad lines
3. try a version without rounded corners

**Comment by ohnozen** [comment]
No problem! I think it's smart to explore all possible logo options so it's not a bother to make these alternates. I've been playing with different controller types and color palettes myself.

![gamer-os_logo_alt_u2](https://user-images.githubusercontent.com/14218478/64890013-25259280-d65e-11e9-98bf-258d5d6b664e.png)

I think I covered all the requests. I'm thinking the top baseline is still the strongest, with the whole logo mid-thickness second, and the d-pad only at mid-thickness taking third.

**Comment by alkazar** [comment]
Wow, thanks! Oh man, I don't know how to decide, lol. I like quite a few of them.

Could we see the top baseline, but with the dpad lines extended more towards the middle? I feel like the gap is a bit too big and the lines are a bit too short now.

The thinner lines look too much like a cross hair I think. Probably better to keep a consistent thickness. I do like the look of some of the mixed thickness variations though, particularly the very bottom left one.

Squared doesnt look as good as the others.

**Comment by ohnozen** [comment]
Okay! Here's some options based on the top baseline. 
![gamer-os_logo_alt_u3](https://user-images.githubusercontent.com/14218478/64902663-26ac8600-d671-11e9-8de4-be6233f66ae7.png)
Tried going back to the original spacing and something halfway between the first version and the latest baseline. I also added a solid option. I'm still torn between if it looks more like the left Steam Controller touch pad or like a health pickup...

**Comment by alkazar** [comment]
that is great, thanks so much. I think we have covered pretty much everything. Thanks for your patience. Now to choose one... it's tough!

**Comment by alkazar** [comment]
I think I have narrowed it down to "og space", "solid" from the above set, and the very original one you did.

**Comment by ohnozen** [comment]
I've been looking at the three on and off today, and I think the "sold" and "og space" are the top choices. I've done some mockups with the Steam BPM boot screen, maybe that will help the decision.

![gamer-os-bpm_mockups-02](https://user-images.githubusercontent.com/14218478/64913886-139bc380-d70e-11e9-82bf-2b02cbbcd313.jpg)
![gamer-os-bpm_mockups-03](https://user-images.githubusercontent.com/14218478/64913887-139bc380-d70e-11e9-98ee-5fd805f83edd.jpg)
![gamer-os-bpm_mockups-01](https://user-images.githubusercontent.com/14218478/64913888-139bc380-d70e-11e9-9993-06131cf0b3c8.jpg)

**Comment by alkazar** [comment]
The thing that keeps bringing me back to the original is the length of the dpad. The smaller ones look more like a shirt button to me, and do not evoke a dpad. However, the original logo looks a bit imbalanced due to the right side being connected. What do you think of the one below I quickly mocked up?
![test2](https://user-images.githubusercontent.com/1140312/64915014-0fca6a00-d72b-11e9-9ca0-ea394729f324.png)

**Comment by alkazar** [comment]
I think I still prefer the original one you did.

**Comment by ohnozen** [comment]
Cool. I think if you're still leaning towards the original then it's safe to say that's the one.
[GamerOS Logos.zip](https://github.com/gamer-os/gamer-os/files/3614217/GamerOS.Logos.zip)

I've attached vector and bitmap versions of the logo for you to use, as well as the font I used to type out "gamerOS" all those versions ago. Wasn't sure if you wanted to use the type, but I wanted to make sure I included most everything.

I'm happy to revisit the logo if you start having second thoughts, and we can work with color options should the need arise.

Now: the website. Did you want the main README content laid out as a single page site?

**Comment by alkazar** [comment]
Awesome, thanks!

Regarding the website, that sounds good. Are you willing to work on that as well?

**Comment by ohnozen** [comment]
Oh definitely. I've got a big block of free time towards the end of the week so I can down and work something solid out. Is there any particular look or layout you're thinking for the site?

**Comment by alkazar** [comment]
I didn't have anything specific in mind, just that it should be a static site that can be hosted on github. Thanks for your effort!

**Comment by alkazar** [comment]
Closing this issue. The new website at https://gamer-os.github.io is good enough for now. Thanks!
