### ISSUE TITLE
Missing Pacman

### ISSUE THREAD

**Issue by MrCraigen** [gamer-os/gamer-os#29]
With the latest version from 1/8 (gameros-2019.08.01-x86_64.iso) there seems to be an issue with Pacman. I get this error when i try to update and install openssh

error: failed to initialize alpm library (could not find or read directory)
(could not find or read directory: /var/lib/pacman/)

When i try to locate the directory for /var/lib/pacman/ it seems to be missing.

**Comment by MrCraigen** [comment]
Got it to work after using the frzr-unlock command :)

**Comment by alkazar** [comment]
Yes, this is intentional.

Please note that any changes you make to the root filesystem will be blown away in the next update. Updates work by replacing the entire root filesystem, thus allowing for unattended upgrades.

frzr-unlock is meant only as a development and debugging tool.

What are you trying to accomplish?

**Comment by MrCraigen** [comment]
Ah I see, quite new with this. First time to hear about the frzr tool

Well i am / was trying to get new linux firmware, nvidia drivers, better wine and proton versions using this:

https://github.com/Tk-Glitch/PKGBUILDS

So if i change the all the things that i mention above, it will be reset after the next update?

**Comment by alkazar** [comment]
That is correct. If you really want to customize gamerOS, you can fork the repo and edit the build.sh file to construct and host your own images via github. You can then point frzr-deploy to your own hosted repo.

However, is there a specific game you are trying to get to work or problem you are trying to solve?

**Comment by MrCraigen** [comment]
Ah no, its more I like to experiment around. Just wanted to have good base to start from and I saw your GamerOS. 

Although, TKG builds does give some better performance with some games. And with his custom Proton some games work better, like Planet Coaster that crashed with the current Proton build.

**Comment by alkazar** [comment]
If you want plain Arch to play around with you can try the arch_installer branch. The installation process is different and results in an Arch install configured similarly to gamerOS. Read the readme in that branch for detailed instructions.

**Comment by MrCraigen** [comment]
I will look in to that aswell, thanks once again for the tips! 

Since there weren't any issue from the first post. I close this one :)
