### ISSUE TITLE
Instructions to install emulators

### ISSUE THREAD

**Issue by smumu** [gamer-os/gamer-os#39]
As a new gamerOS user, I don't know how to install emulators. The readme says: 

> play any game
> out of the box support for playing NES, SNES, Genesis, N64, PlayStation, Wii, Steam games and more (only Steam games are supported out of the box, emulators are pre-installed but currently require manual setup)

Maybe a `emulators.md` could contain instructions for the "manual setup" to help users?
Can be related to https://github.com/gamer-os/gamer-os/issues/24 (creating a website and putting instructions on the website)

BTW, thx for your work :smiley:

**Comment by alkazar** [comment]
Sorry! It is pretty involved and launching games will not be easy either.

I think it will be better to wait. This functionality is being worked on.
Please be patient!

**Comment by smumu** [comment]
No problem, do you have an idea of when it can become easier? 

BTW, it could be nice to have, in the future, a similar procedure to install a media player (like Kodi or VLC). Do you think it will be possible?

**Comment by alkazar** [comment]
No ETA but I hope to have something in the release after next.

Yes, I want to allow installing extra software like kodi via flatpak.
