### ISSUE TITLE
Can't access desktop

### ISSUE THREAD

**Issue by andreashuetter** [gamer-os/gamer-os#41]
I successfully installed gamer-os on my Alienware Steam Machine and it boots into Steam Big Picture Mode. But when I try to access the desktop it does nothing. So I tried Ctrl+Alt+F2 instead, but I could not login there because I don't know the password. So I rebooted the machine and tried to access the grub boot menu while booting (I wanted to select recovery mode to re-set the root password) but this also doesn't work. No matter what keys I press during boot, it never shows the grub boot menu (before, with SteamOS installed this was possible with Shift and Escape keys).

What am I doing wrong??? 

(I must admit that I have zero experience with Arch Linux, because I was only using Ubuntu and SteamOS in the past)

**Comment by sharkwouter** [comment]
That is because gamerOS currently has no desktop

**Comment by andreashuetter** [comment]
OK, thanks for the info!

In this case I will stay with SteamOS as I cannot imagine how to accomplish everything without having access to a desktop environment. Perhaps this is because of me being used to using a desktop environment ever since. Going back completely to command line without any graphical support is not an option for me.

**Comment by alkazar** [comment]
I would ask, what is it that you want to do?

The default user/password is gamer/gamer.

However, the idea with gamerOS is that you shouldn't need to login to the
terminal or use a desktop.

**Comment by andreashuetter** [comment]
Well, I guess I kind of missunterstood what the purpose of gamer-os is. Coming to think about it I guess it does make sense if you see it as a simplistic OS that focuses solely on being a console-like OS for gamers that do not want to touch anything outside the Steam GUI.
I am a heavy, almost fanatic SteamOS user. In fact I really love SteamOS. Of course that's not the only distro I am using, I still have Ubuntu on my laptop and I switched my desktop from Ubuntu to Manjaro last month, but I also own three different Steam Machines (an Alienware ASM100-2980, a Zotac SN970, and a custom built Steam Machine with an i7 and a GTX1080, all of those with SSDs and upgraded memory).
I love SteamOS so much because on one hand it's very easy to handle and on the other handy it's extremely "tweakable", if I invest some time I can get almost anything get to run on it, and sometimes for some things if necessary I can tweak them until they also perform well...
The only downside of SteamOS is that most drivers and libs are heavily outdated and that the repos do not contain everything that might be needed or would be handy to get certain (Windows -)games to run (with Proton). 
When I read that you are building a SteamOS-like distro that derivates from Arch instead of Debian I was hyped. My wishful thinking was that gamer-os would be just like SteamOS, but with newer drivers and libs and with the whole power of the Arch repos. If that would have been the case I would have switched to gamer-os immediately. But to trade my beloved SteamOS for a simple console-like OS where I can only launch things that run out of the box and where I have no chance to get special things to run is not an option for me. But thanks for the reply, I truly respect your efforts for what you are doing and I am sure there are people that are looking for something just like gamer-os. But I guess I will stick to SteamOS.

**Comment by alkazar** [comment]
If you are a power user you do have some options. a) you can install Arch
and the gamerOS components. Or b) you can make your own custom gamerOS
images. It is not very difficult and amounts to adding to the list of
packages. Check out BUILDING.md for details. That way you can build once
and push to all your systems. Others might also want to use your customized
version as well.

One caveat is that even with a desktop installed you cant switch to it from
the big picture UI. You have to edit the lightdm config and restart lightdm.

Hope that helps.

**Comment by telmo1241** [comment]
with ostree wouldn't you make ChimeraOS an immutable system?

**Comment by Bonillac176** [comment]
I have a beelink ser5 mini pc i have chimeraos but i want to go to back to Windows 11 Everytime i tried to flash the anything the system is asking me for gamer password i enter password nothing happens I've tried through the terminal emulator it will ask me for a gamer password also i type gamer and it doesn't work i really need help here i reverting back to Windows.
