### ISSUE TITLE
No indication that an update has installed and a restart is needed to complete the process

### ISSUE THREAD

**Issue by alkazar** [gamer-os/gamer-os#42]

**Comment by sharkwouter** [comment]
Adding ``touch /var/run/reboot-required`` at the bottom on frzr-deploy works in my ssytem after frzr-unlock, but I'm not sure if /var/run is writable on a regular installation.

**Comment by alkazar** [comment]
That's a neat trick. The message says "restart to update SteamOS" though. Not sure if we should use this.

**Comment by sharkwouter** [comment]
I would say that is acceptable, since there isn't really an alternative at the moment

**Comment by alkazar** [comment]
This is now working as of GamerOS 10. Will show a notification for the next update.
