### ISSUE TITLE
[suggestion] Include openssh package

### ISSUE THREAD

**Issue by sharkwouter** [gamer-os/gamer-os#44]
The openssh package is very small and could provide us some benefits:

- Easier file transfer
- Easier debugging
- Running frzr-unlock won't be needed anymore to be able to run ssh

Of course, you wouldn't enable sshd by default, but if it was installed users would have the option to run ``sudo systemctl start sshd`` to run it without needing frzr-unlock and pacman.

**Comment by alkazar** [comment]
Good idea. Added in 599e0e4. Will be available in the next release.
