### ISSUE TITLE
Black Screen During Install

### ISSUE THREAD

**Issue by godtoall82** [gamer-os/gamer-os#47]
When I boot into USB drive and select “install gamerOS”, text appears “SHA256” then goes black. I waited about 5 minutes but screen stayed black. What am I doing wrong?

**Comment by godtoall82** [comment]
So I figured out how to get by the black screen, but now I am running into this when I select the install drive.
![68EA8796-3CB2-4E55-9503-F5A92F312541](https://user-images.githubusercontent.com/56793863/67163460-1ad17500-f33d-11e9-94bf-a05ecd4e443b.jpeg)

Any advice?

**Comment by alkazar** [comment]
Thank you for reporting.

From the log it seems there is a bug in the install script. It is not correctly finding the first partition. I will try to get a fix out ASAP.

May I ask what the initial issue with the black screen was and how you worked around it?

**Comment by godtoall82** [comment]
> Thank you for reporting.
> 
> From the log it seems there is a bug in the install script. It is not correctly finding the first partition. I will try to get a fix out ASAP.
> 
> May I ask what the initial issue with the black screen was and how you worked around it?

Using an Asus ROG Strix mobo, I just disabled CSM compatibility in BIOS.

**Comment by alkazar** [comment]
I think I have fixed the issue, here are the instructions to try it out:
 1. boot into your existing USB installer
 2. select a target disk, when the installer warns about formatting the disk, select "No" ; this will drop you to a shell
 3. use curl to downlad the patched script from here: https://raw.githubusercontent.com/gamer-os/frzr/master/frzr-bootstrap
 4. assign execution permissions to the downloaded script i.e. `chmod +x frzr-bootstrap`
 5. copy the downloaded script to `/usr/bin/frzr-bootstrap
 6. run `./install.sh` to start the installer again

Please let me know how it goes.

**Comment by godtoall82** [comment]
Getting “no file or directory exists” when entering chmod command.

**Comment by alkazar** [comment]
is the file there? i think you have to download it with   `curl https://raw.githubusercontent.com/gamer-os/frzr/master/frzr-bootstrap > frzr-bootstrap`

**Comment by godtoall82** [comment]
Just a heads up, I haven’t given up. Just been too busy to try the fix again. I will try again in the next couple of days.

**Comment by godtoall82** [comment]
> is the file there? i think you have to download it with `curl https://raw.githubusercontent.com/gamer-os/frzr/master/frzr-bootstrap > frzr-bootstrap`

IT WORKED!!!

**Comment by alkazar** [comment]
Thanks for sticking with it. Do you mean that downloading the file worked, or were you able to successfully install GamerOS?

**Comment by godtoall82** [comment]
Yes. Installed successfully following your instructions. Thanks, working great!

**Comment by alkazar** [comment]
Awesome. Thank you for letting me know. I will build new install media with the fix soon.
