### ISSUE TITLE
Bluetooth Pairing

### ISSUE THREAD

**Issue by godtoall82** [gamer-os/gamer-os#51]
My controller unpairs from the system anytime I turn the controller off. I keep having to pair it every time I turn it on. Anyone else have this issue?

**Comment by alkazar** [comment]
Which controller? Which version of GamerOS are you using?

**Comment by godtoall82** [comment]
DS4

I’m not home at the moment but there was an update when I powered on yesterday. I should be on the most recent build.

**Comment by alkazar** [comment]
I heard there was an issue with DS4  and bluetooth on newer kernels. I
wonder if that is it. Google didnt turn up anything recent though.

Have you tried pairing once with a usb cable?

I recall having to do that for a PS3 controller.

**Comment by 200Puls** [comment]
I had the same issue with my DS4. It worked pairing it once with a cable.

**Comment by alkazar** [comment]
@200Puls  would you mind sharing the exact steps you did to get the DS4 working? BTW, is this on GamerOS?

**Comment by 200Puls** [comment]
@alkazar Yes I used GamerOS. I tried pairing the DS4 via bluetooth in the SteamUI which didnt work. Then I plugged it in with usb cable. After that I could pair it with bluetooth.

**Comment by godtoall82** [comment]
This solved the problem. Thanks!
