### ISSUE TITLE
No video output after install (using unraid)

### ISSUE THREAD

**Issue by CaptainHorse** [gamer-os/gamer-os#52]
I've installed gamer-os as a VM on my Unraid server with GPU and peripheral passthrough, install phase worked fine, but afterwards there is no video output on screen (only says "No Signal").

Other VM's work fine with the GPU passthrough so it's not issue with Unraid.

GPU is Radeon R9 280 3GB-VRAM.

**Comment by alkazar** [comment]
Have you ever tried installing SteamOS in the same environment? I have never been able to get SteamOS nor GamerOS to work inside a VM successfully before.

1) There was a recent issue reported with boot up being extremely slow due to lack of entropy; it could be that it just needs a few minutes to boot. This problem is solved in a version of GamerOS that is currently in testing. You could try waiting for 10 minutes to rule out this possibility.

2) It could simply be GamerOS has trouble detecting the resolution of the screen. Have you made sure your monitor/TV is on and plugged in before starting the system?

3) Can you switch to tty? If you can get a tty, try running `systemctl status lightdm` to see if there were any errors.

**Comment by CaptainHorse** [comment]
1. Tested, no output after 30 minutes
2. Plugged in and working fine, Unraid terminal shows fine before handing over the GPU
3. There is no output at all on screen or even VNC, is SSH or Telnet possible?

**Comment by alkazar** [comment]
You cant get to a tty with ctrl-alt-f3?

an ssh server is installed, but not enabled by default. You would have to chroot in post install and run `systemctl enable sshd`, before restarting.

**Comment by CaptainHorse** [comment]
Negative, cannot get to TTY, not through device passthrough or VNC (tested both Cirrus and QXL, both show the "Guest has not initialized the display (yet)" message).

**Comment by alkazar** [comment]
Did you install in bios mode or efi?

I wonder if something is going wrong during boot but the quiet boot setup is swallowing the output. Perhaps try removing the kernel parameters after and including the "quiet" option in the syslinux/syslinux.cfg file. It will be on different partitions depending on whether you installed in bios mode or efi. That might possibly give you some output to work with.

**Comment by CaptainHorse** [comment]
The install was made on UEFI to support GPU passthrough, using Q35-4.0.1 and OVMF.

How would I go about editing the syslinux config file? I tried opening and modifying the image using 7-Zip but it would just give me permission errors, then I tried downloading the whole image and editing it locally which gave some "Operation is not supported" errors.

**Comment by alkazar** [comment]
You dont edit the image, it does not contain syslinux.cfg.

Mount the first partition of an existing install (label frzr-efi). The file should be EFI/syslinux/syslinux.cfg.

**Comment by CaptainHorse** [comment]
What I meant by image is the virtual disk file (.img file, VirtIO type) where the whole OS is.
syslinux config lives in `vdisk1.img/0.img/EFI/syslinux`

I'll try to extract the whole image (and the inner image) to try and modify the config that way, will take a while since it's a 30GB image.

**Comment by alkazar** [comment]
Can you boot the image with either the GamerOS installer or the live/install cd of another distro?

I do this often with virt-manager/qemu.

**Comment by CaptainHorse** [comment]
When I try to boot into the image through the virtual bios boot menu, it quickly flashes black and then returns back to the menu.

Editing syslinux config file yielded no different results either.

**Comment by alkazar** [comment]
Sorry, not sure how to help further. I have had no luck getting SteamOS or GamerOS to run in a VM either.

**Comment by thomasvt1** [comment]
Hey, so I actually got GamerOS working on unraid, still having some issues with sound tho (msi interrupt problems) - but here's my config. Hope it helps :)

![image](https://user-images.githubusercontent.com/2271011/72216094-bd545b00-351c-11ea-9768-3fc9fe96e620.png)
![image](https://user-images.githubusercontent.com/2271011/72216097-c6ddc300-351c-11ea-8867-0c9db7cc26e6.png)

Also have you tried unbinding the GPU from unraid? In some VM's that's required.
```#!/bin/bash

echo 0 > /sys/class/vtconsole/vtcon0/bind
echo 0 > /sys/class/vtconsole/vtcon1/bind
echo efi-framebuffer.0 > /sys/bus/platform/drivers/efi-framebuffer/unbind```

Let me know if it works

**Comment by thomasvt1** [comment]
So after playing with GamerOS for a while I'd like to document my additional changes which work well with unraid.

**Using unraid mounts;**
First make sure you have 'unraid share' and 'unraid mount tag' set like the screenshot above, then run ``frzr-unlock``. After this install nano (with pacman)

Then create a service to mount our unraid share
``sudo nano /etc/systemd/system/steammount.service``
Save it with the following content
```
[Unit]
Description=Start Steam Mount
 
[Service]
ExecStart=mount -t 9p -o trans=virtio "games" /home/gamer/.local/share/Steam/steamapps
 
[Install]
WantedBy=multi-user.target
```
Then enable this service with ``sudo systemctl enable steammount.service``

**Fixing MSI interrupts (Nvidia GPU passtrough)**
Make sure you still have ``frzr-unlock`` enabled (not restarted after unlocking) and have nano installed or know how vim works.

Let's enable interrupts
``sudo nano /etc/modprobe.d/gameros.conf``
And add the following line at the end of the file
``options snd-hda-intel enable_msi=1``

Now save the file and reboot :)

**Comment by collinthorn** [comment]
I, too, was able to get GamerOS running in an Unraid VM. It took some trial-and-error, but it works. I couldn't start with thomasvt1's setup, however - it would fail during installation while trying to set up frzr.

To get it working, I mainly fiddled with the number of CPUs/threads and the two memory allocations, but I think the critical point was getting through installation using VNC/Cirrus for graphics up until the image became mostly gobbledygook but with the visible Steam Big Picture cursor. Once I saw that icon I knew it had installed, I force quit the VM in Unraid and went ahead and matched thomasvt1's pictured setup above (without the Unraid share specifics, which I personally didn't need).

For a while I didn't even need the MSI interrupt-related edits. But then, for whatever reason, I did, so I used thomasvt1's notes above and figured it out. I hope thomasvt1 will allow me to add some detail to what he wrote for getting those working, as well as some changes related the new #15 version of GamerOS (btw, I couldn't get Vim working properly, so I had to install nano...that's included below):

Ctrl-Alt-F3 to get to command line from Big Picture
login: gamer    password: gamer
sudo frzr-unlock
sudo pacman -Sy
sudo pacman -S nano

For GamerOS 12: sudo nano /etc/modprobe.d/gameros.conf
For GamerOS 15: sudo nano /etc/modprobe.d/system-tweaks.conf

Scroll down to the bottom of this list of commands/tweaks using the arrow keys and add:
options snd-hda-intel enable_msi=1

Save and exit by Ctrl-X, then answer the prompts.
Then "reboot"

All credit to thomasvt1. He did the technical discovery work. Maybe this will prove helpful for others trying to perform the same kind of setup as the two of us.

**Comment by alkazar** [comment]
If anyone is installing GamerOS 15, it should no longer be necessary to run `frzr-unlock` to get this working with the instructions posted by @thomasvt1 and @collinthorn .

**Comment by alkazar** [comment]
@thomasvt1 any idea if it is safe to add `options snd-hda-intel enable_msi=1` by default? I would expect not.

**Comment by thomasvt1** [comment]
> @thomasvt1 any idea if it is safe to add `options snd-hda-intel enable_msi=1` by default? I would expect not.

According to my fast research some devices misbehave when it is enabled. I'd keep it removed by default.

A solution may be to detect if running in a VM and then enabling enable_msi

**Comment by alkazar** [comment]
Closing since no action required.
