### ISSUE TITLE
Can't change Display resolution from detected default.

### ISSUE THREAD

**Issue by ChojinDSL** [gamer-os/gamer-os#68]
I have my steam machine connected to a 4K TV. But I'd rather have it set to 1080p. Unfortunately, after installation in the Steam Big Picture UI, the resolution option only allows me scale the borders, but doesn't give me any option for choosing another resolution.

**Comment by alkazar** [comment]
This is a limitation of the Steam client which we cannot modify since it is not open source.

However, `steamos-compositor-plus` does allow you to specify a custom resolution and refresh rate through a configuration file.

See https://github.com/gamer-os/steamos-compositor-plus for details

**Comment by ChojinDSL** [comment]
Ah ok, thanks. 

You know, I could have sworn that in some incarnation of steam big picture, I was able to change the resolution. Maybe my mind is playing tricks on me, or maybe that was on windows.

**Comment by alkazar** [comment]
It has never been possible as far as I know. Not sure about Windows.

**Comment by alkazar** [comment]
I have created this related issue: https://github.com/gamer-os/steam-buddy/issues/28

**Comment by laurinneff** [comment]
> 
> 
> It has never been possible as far as I know. Not sure about Windows.

I just tried it out on both my Windows laptop and my Linux PC and on both I'm able to change the resolution
