### ISSUE TITLE
How do I install using Wifi?

### ISSUE THREAD

**Issue by RafaelRestolho** [gamer-os/gamer-os#70]
I use a notebook for work and I'm always connected to the wifi, I would like to know if it is possible to install without using a cable

srry for my bad english.
thx

**Comment by alkazar** [comment]
I wouldnt recommend installing on a notebook.
GamerOS requires a dedicated hard drive and doesnt really allow for dual booting. It is also not a general operating system and cant do anything other than play games.

If you still want to install it, you could connect a phone via usb and share the wifi connection.
