### ISSUE TITLE
Updated kernel

### ISSUE THREAD

**Issue by 200Puls** [gamer-os/gamer-os#72]
Hi,

is there any plan to upgrade the kernel to Linux 5.5 soon? I need the most recent kernel for support of my RX5500xt. Or can I manually upgrade the kernel?

**Comment by sharkwouter** [comment]
Yes, there is a new version currently in testing. It think that has the kernel you need. It will likely be released soon. Otherwise you could install the testing version. You can find instructions on how to do so here: https://github.com/gamer-os/gamer-os/wiki/FAQ#how-can-i-help-test-gameros

**Comment by alkazar** [comment]
GamerOS 15 with Linux kernel 5.5.4 has now been released.

**Comment by 200Puls** [comment]
Thanks, that version is working great.
