### ISSUE TITLE
ERROR: device 'LABEL=frzr_root' not found

### ISSUE THREAD

**Issue by ChojinDSL** [gamer-os/gamer-os#75]
I get the following error message at first boot after installation:

ERROR: device 'LABEL=frzr_root' not found. Skipping fsck.
mount: /new_root: can't find LABEL=frzr_root.
Your are now being dropped into an emergency shell.

Any quick fix I can do via the emergency shell?

**Comment by alkazar** [comment]
What are you installing to? I have seen this before when installing to VMs.

**Comment by alkazar** [comment]
This seems to be an issue with the initramfs image. I believe I have fixed it. I will push a testing build out soon.

**Comment by ChojinDSL** [comment]
I'm trying to install Gamer OS on small form factor PC. (Intel NUC Hades Canyon).
I run a multiboot system. Windows 10 as well as Pop OS. But I attached a separate USB Harddrive to which I installed Gamer OS. Other than that the PC has two internal NVME SSDs installed.

The strange thing is, I've tried Gamer OS a couple of weeks ago (Installing to one of the internal NVME Drives) and it went fine. I just reverted to my old set up again since I didn't have time to customize everything the way I had it before.

**Comment by alkazar** [comment]
Yeah, installing to the USB drive is causing the failure.

**Comment by ChojinDSL** [comment]
Ah I see. Let me know if you need any further information for debugging.

**Comment by alkazar** [comment]
Fixed in a77e91f
