### ISSUE TITLE
Login to terminal "authentication failure"

### ISSUE THREAD

**Issue by Tiger862000** [gamer-os/gamer-os#79]
Hi,
I change with CRTL+ALT+F3 to the terminal. 
A login with standard credentials (gamer/gamer) does not work.
Output: authentication failure

What am I doing wrong here?

**Comment by alkazar** [comment]
Did you change your password in the past?

**Comment by Tiger862000** [comment]
No, it's a fresh install. Just installed some games within steam. Nothing else.

**Comment by alkazar** [comment]
That is bizarre. I don't know how that is possible.

Just to be certain:
You enter "gamer" for the username, press enter, then type "gamer" for the password and hit enter?

Are you maybe using a keyboard with a unique key layout?

**Comment by Tiger862000** [comment]
If I misspell ie type anything else it gives me "Login incorrect"
So I don't think I mistyped or have problems due to keyboard layout.

**Comment by alkazar** [comment]
If you can't log in, I don't know how you can send me log files.

**Comment by alkazar** [comment]
The only thing I can think of is maybe some service required for authentication failed. Have you tried the old "turn it off and on again"?

I just tried a fresh install in a VM and am not having this problem.
