### ISSUE TITLE
steam buddy: Installation game/app causes "Error: 500 Internal Server Error"

### ISSUE THREAD

**Issue by Tiger862000** [gamer-os/gamer-os#80]
Hi,
installation of any game or application through steam buddy client (opening gameros.local on my laptop browser) creates following error "Error: 500 Internal Server Error".
Restart of steam: didn't resolve the issue
Restart of the system: didn't help either :-/

Please help.

**Comment by alkazar** [comment]
What were you trying to install exactly? A flatpak app or ROM?

**Comment by Tiger862000** [comment]
Install of TuxKart or Install of MarioKart64 for example.
But I'm facing problems with my sata controller apparently - read write errors. Once I fixed that I will report back if the problem still persists.
