### ISSUE TITLE
Just Cause 3 won't launch

### ISSUE THREAD

**Issue by Mohandevir** [gamer-os/gamer-os#87]
I'm coming from an Ubuntu 19.10 installation where Just Cause 3 worked perfectly, ootb, with proton 5.0.5. 

Now the game launch to a black screen with the intro sound being choppy and slow... It feels like earlier versions of Proton even if I force Proton 5.0.5 in the launch option.

Could it be related to the Nvidia Driver version? I was using the latest version, on Ubuntu 19.10 with the gpu driver ppa.

The other game that had Denuvo issues, before Proton 5.0.4, (Batman Arkham Knight) works flawlessly.

Sorry! I have a Little more spare time, lately.

Thanks for your support!

**Comment by alkazar** [comment]
Thanks for the report.
I don't have this game to be able to check and don't know what the problem could be.
Do you happen to recall what version of the Nvidia driver you were using before?

I have reached out to our Discord community to see if anyone can help with this game.

**Comment by Mohandevir** [comment]
Thanks!
I was using the 440.64 driver.

**Comment by alkazar** [comment]
GamerOS 15 (current version) has 440.59. 440.64 will be in the next release coming soon.
Don't know if that will make the difference. I guess we'll see.

**Comment by Mohandevir** [comment]
I don't know if it's related, but there are many games that just won't launch, when using Proton 5.0.5... Any Lego games I tried or Sonic & All-Star Racing Transformed Collection are getting stuck on a white frame. I must revert to Proton 4.11 to get the game started. It's a problem I didn't have on my Ubuntu setup (I was using the standard SteamOS-Compositor, on Ubuntu). Wild guess from my part, but could it be related to the SteamOS-Compositor-Plus color frame tweak?

**Comment by Mohandevir** [comment]
It seems I was wrong... Fired up Sonic on a secondary PC (i7-3770 and GTX 960 with driver 440.64) on a brand new install of Ubuntu with vanilla SteamOS-Compositor and Proton 5.0.5... Same problem. I hear the sound of the game but the display is white.
