### ISSUE TITLE
Need help installing...

### ISSUE THREAD

**Issue by robguenther** [gamer-os/gamer-os#94]
I put GamerOS .iso on a disc and then put it in an old computer and booted from disc. Looked like it was working at first, but lands on this error...

+ curl -L -s https://gamer-os.github.io/gamer-os/repos/default
Installation failed. 
archiso#

**Comment by robguenther** [comment]
![IMG_20200418_131526308](https://user-images.githubusercontent.com/6858182/79653973-be2e0600-8177-11ea-9a43-b6a988e49ea9.jpg)

**Comment by sharkwouter** [comment]
It looks like you may have connection issues. Is your computer connected by a wired network connection?

**Comment by robguenther** [comment]
Yes. But let me try a different port. Thanks for the quick response!

**Comment by robguenther** [comment]
Hmmm... Might be the cable. I'll have to find a different one.

**Comment by sharkwouter** [comment]
Okay, good luck!
